(() => {
'use strict';
const root=document.getElementById('italy-tree-app');
const el=id=>root.querySelector('#'+id);
const clone=value=>JSON.parse(JSON.stringify(value));
const sample=day=>'2026-10-'+String(day).padStart(2,'0');
const item=(id,parent,title,kind,days,description,extra={})=>({id,parent,trip:'italy',title,kind,start:days.length?sample(Math.min(...days)):null,end:days.length?sample(Math.max(...days)):null,description,note:'',...extra});
let nodes={
 italy:item('italy',null,'意大利旅行','trip',[1,7],'从罗马的街巷，到佛罗伦萨的艺术，再给乡间风景留一点时间。'),
 rome:item('rome','italy','罗马','place',[1,2],'抵达、安顿，在街头慢慢进入旅行的节奏。',{location:[.61,.73]}),
 arrival:item('arrival','rome','抵达与酒店安顿','activity',[1],'结合航班与酒店位置安排接驳，抵达后留出休息时间。',{slot:'抵达后'}),
 romeWalk:item('romeWalk','rome','城市漫步','activity',[2],'探索感兴趣的街区，具体停留点可以继续细化。',{slot:'白天'}),
 florence:item('florence','italy','佛罗伦萨','place',[3,4],'一场期待的博物馆参观，也有走走停停的街区时光。',{location:[.37,.31]}),
 uffizi:item('uffizi','florence','乌菲齐美术馆观光','plan',[3],'围绕喜欢的作品慢慢看，参观前后保留休息和衔接时间。',{pace:'relaxed',location:[.64,.49],locationLabel:'乌菲齐美术馆'}),
 museumArrival:item('museumArrival','uffizi','到馆与入场','activity',[3],'确认出发位置、票面场次和入场要求后，再细化到馆方式。',{slot:'参观前'}),
 museumVisit:item('museumVisit','uffizi','馆内参观','activity',[3],'挑选感兴趣的作品与展厅，按照自己的节奏停留。',{slot:'参观中'}),
 museumAfter:item('museumAfter','uffizi','午餐与休息','activity',[3],'参观后留一段空白，根据当天体力选择用餐和后续活动。',{slot:'参观后',optional:true}),
 florenceWalk:item('florenceWalk','florence','街区散步与自由时间','activity',[4],'不急着填满这一天，散步、咖啡或临时发现都可以。',{slot:'自由安排',optional:true,location:[.35,.64],locationLabel:'街区散步'}),
 drive:item('drive','italy','乡间自驾计划','plan',[5,6],'预留两天探索乡间；起终点、路线与停留地点等待补充。'),
 driveFirst:item('driveFirst','drive','沿途风景与停留','plan',[5],'根据起终点比较路线，并留出观景和休息的余量。'),
 driveFirstStop:item('driveFirstStop','driveFirst','观景与午餐停留','activity',[5],'明确真实路线后再选择观景和用餐地点。',{slot:'途中'}),
 driveSecond:item('driveSecond','drive','继续探索与抵达','plan',[6],'根据下一处住宿位置安排出发和抵达。'),
 driveSecondStop:item('driveSecondStop','driveSecond','抵达前的一段探索','activity',[6],'当天可以根据体力和抵达时间决定是否停留。',{slot:'抵达前',optional:true}),
 departure:item('departure','italy','返程','activity',[7],'核对航班与出发地点，为收拾行李和前往机场留出时间。'),
 preparation:item('preparation','italy','旅行准备','collection',[],'整理预订、材料和出发前需要确认的事项。'),
 museumTicket:item('museumTicket','preparation','美术馆购票与入场准备','guide',[],'从已有门票和参观计划出发，确认需要做的准备。',{steps:[{title:'确认参观日期与门票场次',detail:'核对已有订单；如果尚未购买，保留待选场次。',done:false},{title:'查看官方购票与入场说明',detail:'确认适用于参观日期的预约和入口要求。尚未查询实时信息。',done:false},{title:'保存票据与到馆信息',detail:'准备可出示的凭据，记录出发位置、入口和交通方式。',done:false}]}),
 carRental:item('carRental','preparation','租车与取还车准备','guide',[],'两段自驾共用这份准备，进度在各处同步。',{steps:[{title:'明确用车条件',detail:'补充起终点、日期、人数、行李及驾驶者情况。',done:false},{title:'比较车辆与条款',detail:'按实际日期核实库存、价格、押金、保险和取还车条件。',done:false},{title:'记录取还车信息',detail:'完成选择后保存真实凭据、门店地址和办理说明。',done:false}]}),
 shopping:item('shopping',null,'佛罗伦萨购物半日','plan',[4],'先留住这个想法，决定后再放进佛罗伦萨的行程。',{trip:null}),
 shoppingGoal:item('shoppingGoal','shopping','明确想买的商品','activity',[4],'补充商品类别、预算与偏好。',{trip:null})
};
let relations=[{from:'uffizi',to:'museumTicket'},{from:'driveFirst',to:'carRental'},{from:'driveSecond',to:'carRental'}];
let currentId='italy',mode='plan',history=[],serial=0,revision=0;
let mapSelection=null,mapZoom=null,mapSvg=null;
const expanded=new Set(['italy','florence']);
const conversations={};
const labels={trip:'一趟旅行',place:'目的地',plan:'一部分计划',activity:'具体安排',collection:'旅行准备',guide:'行动指引'};
const children=id=>Object.values(nodes).filter(n=>n.parent===id);
const planChildren=id=>children(id).filter(n=>!['guide','collection'].includes(n.kind));
function subtree(id){return [nodes[id],...children(id).flatMap(n=>subtree(n.id))];}
function ancestors(id){const result=[],seen=new Set();let n=nodes[id];while(n&&!seen.has(n.id)){result.unshift(n);seen.add(n.id);n=nodes[n.parent];}return result;}
const path=id=>ancestors(id).map(n=>n.title).join(' › ');
function validDate(value){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(value+'T00:00:00Z'))&&new Date(value+'T00:00:00Z').toISOString().slice(0,10)===value;}
const epoch=s=>Date.parse(s+'T00:00:00Z');
const shift=(s,delta)=>s?new Date(epoch(s)+delta*86400000).toISOString().slice(0,10):null;
const dayDiff=(a,b)=>(epoch(a)-epoch(b))/86400000;
const pretty=(s,year=false)=>s?(year?s.slice(0,4)+' 年 ':'')+Number(s.slice(5,7))+' 月 '+Number(s.slice(8,10))+' 日':'日期待定';
function dates(n,year=false){if(!n.start)return '日期待定';return pretty(n.start,year)+(n.end!==n.start?' — '+pretty(n.end,n.end.slice(0,4)!==n.start.slice(0,4)):'')+(n.inherited?' · 暂定':'');}
function allDates(n){if(!n.start||!n.end)return [];const count=dayDiff(n.end,n.start);return Array.from({length:Math.min(count+1,367)},(_,i)=>shift(n.start,i));}
function related(id){const ids=new Set(subtree(id).map(n=>n.id));ancestors(id).forEach(n=>ids.add(n.id));const found=new Set(relations.filter(r=>ids.has(r.from)).map(r=>r.to));subtree(id).filter(n=>n.kind==='guide').forEach(n=>found.add(n.id));return [...found].map(id=>nodes[id]).filter(Boolean);}
const progress=n=>(n.steps||[]).filter(s=>s.done).length+' / '+(n.steps||[]).length;
function create(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function button(text,action,cls=''){const b=create('button',cls,text);b.type='button';b.addEventListener('click',action);return b;}
function notice(text){el('ih-notice').textContent=text;}
function checkpoint(){history.push(clone({nodes,relations,currentId,mode}));revision++;}
function closeForms(){['date','add','move'].forEach(k=>el('ih-'+k+'-form').hidden=true);el('ih-menu').open=false;}
function conversation(){return conversations[currentId]||(conversations[currentId]={messages:[],proposal:null,draft:''});}
function go(id,preserveMode=false){if(!nodes[id])return;conversation().draft=el('ih-ai-input').value;currentId=id;if(!preserveMode)mode='plan';ancestors(id).forEach(n=>expanded.add(n.id));closeForms();mapSelection=null;if(globalThis.matchMedia?.('(max-width:600px)').matches)el('ih-directory').open=false;render();notice('');}
function setMode(next){mode=next;closeForms();render();}
function renderTree(){
 const nav=el('ih-tree');nav.replaceChildren();
 function branch(n){const li=create('li'),row=create('div','tree-row'),kids=children(n.id);if(kids.length){const t=button(expanded.has(n.id)?'⌄':'›',()=>{expanded.has(n.id)?expanded.delete(n.id):expanded.add(n.id);renderTree();},'tree-toggle');t.setAttribute('aria-label',(expanded.has(n.id)?'收起':'展开')+n.title);t.setAttribute('aria-expanded',String(expanded.has(n.id)));row.append(t);}else row.append(create('span','tree-dot'));const b=button(n.title,()=>go(n.id),'tree-name');b.dataset.node=n.id;if(currentId===n.id)b.setAttribute('aria-current','page');row.append(b);li.append(row);if(kids.length&&expanded.has(n.id)){const ul=create('ul','tree-children');kids.forEach(k=>ul.append(branch(k)));li.append(ul);}return li;}
 const ul=create('ul');ul.append(branch(nodes.italy));nav.append(ul);
 const loose=el('ih-detached');loose.replaceChildren();Object.values(nodes).filter(n=>!n.parent&&n.id!=='italy').forEach(n=>loose.append(button('＋ '+n.title,()=>go(n.id))));if(!loose.childElementCount)loose.append(create('p','small','所有想法都已放进行程'));
}
function renderCards(n){const list=el('ih-cards');list.replaceChildren();const kids=n.kind==='collection'?children(n.id):planChildren(n.id);el('ih-child-heading').textContent=n.kind==='trip'?'这趟旅行，慢慢展开':kids.length?'接下来，探索这一部分':'留给这次体验的时间';el('ih-inline-add').hidden=n.kind==='collection';el('ih-open-time').hidden=n.kind==='collection';
 for(const child of kids){if(child.kind==='guide'){list.append(guideButton(child));continue;}const row=button('',()=>go(child.id),'plan-row');row.dataset.open=child.id;const d=create('span','date-block');d.append(create('span','',child.start?Number(child.start.slice(5,7))+' 月':'待定'),create('b','',child.start?child.start.slice(8)+(child.end!==child.start?'–'+(child.end.slice(0,7)!==child.start.slice(0,7)?Number(child.end.slice(5,7))+'/':'')+child.end.slice(8):''):'·'));const body=create('span');body.append(create('span','plan-title',child.title),create('span','plan-description',child.description));const descendants=planChildren(child.id);body.append(create('span','plan-meta',descendants.length?descendants.length+' 个安排 · '+descendants.slice(0,2).map(x=>x.title).join(' / '):child.optional?'可选 · 根据当天状态决定':child.inherited?'日期暂沿用上级':'可继续细化'));row.append(d,body,create('span','row-arrow','›'));list.append(row);}
 el('ih-leaf').hidden=!!kids.length;el('ih-leaf-text').textContent=n.description;const guides=related(n.id);el('ih-related-summary').hidden=!guides.length||n.kind==='collection';el('ih-related-label').textContent=guides.length+' 项相关准备';
}
function guideButton(n){const b=button('',()=>go(n.id),'guide-row');b.dataset.guide=n.id;const text=create('span');text.append(create('strong','',n.title),create('span','small','待核实 · 与计划共用'));b.append(text,create('span','guide-state',progress(n)+' ›'));return b;}
function renderDates(n){const area=el('ih-calendar');area.replaceChildren();const leaves=subtree(n.id).filter(x=>!['guide','collection'].includes(x.kind)&&!planChildren(x.id).length);const datesSet=new Set(allDates(n));leaves.forEach(x=>allDates(x).forEach(d=>datesSet.add(d)));el('ih-calendar-summary').textContent='以当地日历日期整理 · 当前范围：'+n.title+' · 示例日期';
 if(!datesSet.size)area.append(create('p','small','还没有确定日期，可以通过对话或标题下的日期入口补充。'));
 for(const date of [...datesSet].sort()){const section=create('section','calendar-day');section.dataset.calendarDate=date;const label=create('div','calendar-label');label.append(create('span','',Number(date.slice(5,7))+' 月'),create('strong','',date.slice(8)),create('span','',new Intl.DateTimeFormat('zh-CN',{weekday:'short',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'))));const events=create('div','calendar-events');for(const leaf of leaves.filter(x=>x.start<=date&&x.end>=date)){const b=button('',()=>go(leaf.id),'event');b.dataset.dateNode=leaf.id;const text=create('span');text.append(create('span','',leaf.title),create('span','small',ancestors(leaf.id).slice(1,-1).map(x=>x.title).join(' / ')||labels[leaf.kind]));b.append(text,create('span','event-slot',leaf.slot||'时间待定'));events.append(b);}if(!events.childElementCount)events.append(create('p','open-time','这一天暂时留白'));section.append(label,events);area.append(section);}
 const unscheduled=leaves.filter(n=>!n.start);if(unscheduled.length){area.append(create('h3','','日期待定'));unscheduled.forEach(n=>area.append(button(n.title,()=>go(n.id),'event')));}
}
function renderGuide(n){el('ih-guide-progress').textContent=progress(n)+' 项准备已记录';const list=el('ih-checks');list.replaceChildren();(n.steps||[]).forEach((s,i)=>{const li=create('li'),label=create('label','check-label'),box=create('input'),body=create('span');box.type='checkbox';box.checked=s.done;box.dataset.step=i;body.append(create('strong','',s.title),create('span','small',s.detail));label.append(box,body);li.append(label);list.append(li);box.addEventListener('change',()=>{checkpoint();n.steps[i].done=box.checked;render();notice('准备进度已同步到所有关联计划。');});});const links=el('ih-backlinks');links.replaceChildren();relations.filter(r=>r.to===n.id).forEach(r=>links.append(button(path(r.from),()=>go(r.from),'event')));const source=el('ih-guide-source');source.replaceChildren();if(n.source){const a=create('a','source-link','查看官方信息 ↗');a.href=n.source;a.target='_blank';a.rel='noopener';source.append(a);}}
function conflicts(n){return subtree(n.id).filter(x=>x.parent&&x.start&&nodes[x.parent].start&&(x.start<nodes[x.parent].start||x.end>nodes[x.parent].end));}
function render(){const n=nodes[currentId];renderTree();const crumbs=el('ih-breadcrumb');crumbs.replaceChildren();ancestors(currentId).forEach((a,i)=>{if(i)crumbs.append(create('span','','/'));const b=button(a.title,()=>go(a.id));b.dataset.crumb=a.id;crumbs.append(b);});el('ih-kind').textContent=labels[n.kind]+(n.trip?' · 个人草案':' · 独立想法');el('ih-title').textContent=n.title;el('ih-dates').textContent=dates(n,true)+'  ↗';el('ih-dates').hidden=['guide','collection'].includes(n.kind);el('ih-description').textContent=n.description;const warnings=conflicts(n);el('ih-context').hidden=!warnings.length&&!!n.trip;el('ih-context').textContent=warnings.length?warnings.map(x=>x.title).join('、')+' 的日期超出上级范围，可修改日期或调整归属。':'这个想法还没放进行程，可从右上角菜单加入意大利旅行。';el('ih-undo').disabled=!history.length;el('ih-add').hidden=['guide','collection'].includes(n.kind);el('ih-move').hidden=n.id==='italy'||['guide','collection'].includes(n.kind);el('ih-menu').hidden=['guide','collection'].includes(n.kind);const isGuide=n.kind==='guide';for(const v of ['plan','date','map','prep']){el('ih-'+v+'-view').hidden=isGuide;el('ih-'+v+'-view').setAttribute('aria-pressed',String(mode===v));el('ih-'+v+'-panel').hidden=isGuide||mode!==v;}el('ih-guide-panel').hidden=!isGuide;el('ih-notes-section').hidden=n.kind==='collection';el('ih-notes').value=n.note;el('ih-prep-count').textContent=related(n.id).length||'';
 if(isGuide)renderGuide(n);else{renderCards(n);renderDates(n);const list=el('ih-prep-list');list.replaceChildren();related(n.id).forEach(g=>list.append(guideButton(g)));if(!list.childElementCount)list.append(create('p','map-empty','还没有相关准备。告诉 AI 想了解什么，它会先给出准备草案。'));if(mode==='map')renderMap(n);}
 renderChat();
}
function openAdd(){closeForms();el('ih-add-form').hidden=false;el('ih-add-title').value='';el('ih-add-parent').textContent='加入：'+path(currentId)+' · 日期暂沿用上级';el('ih-add-title').focus();}
function openMove(){closeForms();el('ih-move-form').hidden=false;const excluded=new Set(subtree(currentId).map(n=>n.id));const select=el('ih-parent-select');select.replaceChildren();Object.values(nodes).filter(n=>n.trip==='italy'&&!excluded.has(n.id)&&!['guide','collection'].includes(n.kind)).forEach(n=>{const o=create('option','',path(n.id));o.value=n.id;select.append(o);});select.value=nodes[currentId].parent||'italy';}
function id(){return 'custom-'+(++serial);}
function openAI(text=''){if(text){el('ih-ai-input').value=text;conversation().draft=text;}el('ih-ai-panel').scrollIntoView?.({behavior:'smooth',block:'nearest'});el('ih-ai-input').focus();}
function renderChat(){const c=conversation(),n=nodes[currentId];el('ih-ai-scope').textContent=path(currentId);const log=el('ih-ai-log');log.replaceChildren();if(!c.messages.length){const msg=n.kind==='guide'?'把需要了解的事情告诉我，我们一起补全准备步骤。':n.id==='italy'?'这趟旅行已经有了轮廓。想调整节奏、细化某一部分，或提前弄清楚怎么做，都可以从这里开始。':'我们正在一起安排「'+n.title+'」。说说你想改变什么，我会先给出这一部分的修改建议。';log.append(create('div','ai-message assistant',msg));}for(const message of c.messages){const box=create('div','ai-message '+message.role);box.append(create('span','message-scope',message.role==='user'?'你':message.target?'AI · '+message.target:'AI · 模拟回复'),create('span','',message.text));log.append(box);}const suggestions=el('ih-suggestions');suggestions.replaceChildren();const prompts=n.kind==='guide'?['补充需要确认的材料和办理步骤']:['把这部分安排得轻松一点',n.id==='italy'?'补全佛罗伦萨的具体安排':'补全这部分的具体安排',n.id==='uffizi'?'增加购票和入场准备':'增加这部分的出发前准备'];if(!c.messages.length)prompts.forEach(p=>suggestions.append(button(p+' ↗',()=>send(p))));el('ih-ai-input').value=c.draft;renderProposal();}
function renderProposal(){const c=conversation(),p=c.proposal,area=el('ih-proposal');area.replaceChildren();area.hidden=!p;if(!p)return;area.append(create('p','proposal-title',p.title),create('p','small','作用于：'+path(p.target)));for(const diff of p.diffs){const row=create('div','proposal-item');row.append(create('strong','',diff.title));if(diff.before)row.append(create('p','proposal-before',diff.before));row.append(create('p','proposal-after',diff.after));area.append(row);}if(p.warning)area.append(create('p','small',p.warning));const actions=create('div','proposal-actions');const apply=button('采用这次修改',applyProposal,'primary');apply.id='ih-apply-proposal';apply.disabled=p.baseRevision!==revision;actions.append(apply,button('暂不修改',()=>{c.proposal=null;c.messages.push({role:'assistant',text:'先保留原来的安排。你可以继续调整想法。'});renderChat();}));area.append(actions);if(p.baseRevision!==revision)area.append(create('p','small','计划已有更新。这份建议已过期，请重新发送需求以生成最新预览。'));}
function changesForShift(target,start){const n=nodes[target];if(!n.start)return [{type:'set',id:target,field:'start',value:start},{type:'set',id:target,field:'end',value:start}];const delta=dayDiff(start,n.start);return subtree(target).filter(n=>n.start).flatMap(n=>[{type:'set',id:n.id,field:'start',value:shift(n.start,delta)},{type:'set',id:n.id,field:'end',value:shift(n.end,delta)},{type:'set',id:n.id,field:'inherited',value:false}]);}
function makeGuide(target,title,topic){const existing=related(target).find(n=>n.title===title);if(existing)return {existing};const parent=nodes[target].trip==='italy'?'preparation':target;const gid=id();let steps;if(topic==='museum')steps=[['核对日期和现有门票','记录已购票的场次、票种和订单；未购买的部分保持待选。'],['核实官方预约与入场要求','按实际参观日查询开放、入口、随身物品和到馆要求。'],['补全到馆与参观后的衔接','根据出发地点安排交通，并留出休息时间。']];else if(topic==='border')steps=[['补充适用情境','记录护照签发地、出发地、目的地、中转、旅行日期和同行者情况。'],['查证官方材料与申报要求','根据上述情境查询官方入境及海关信息；目前尚未核实任何适用规则。'],['保存办理入口与待办','把核实后的材料、申报入口和需提前完成的事项记录在这里。']];else if(topic==='rental')steps=[['确认实际用车需求','补充起终点、取还车日期、人数、行李与驾驶者条件。'],['核实车型和租赁条件','按实际日期查询库存、费用、押金、保险及所需材料。'],['保存取还车说明','明确门店地址、营业时间、验车与还车流程。']];else steps=[['整理已经确定的安排','补充订单、日期、地点和同行者的必要条件。'],['核实需要提前办理的事项','结合这部分的活动查询预约、材料和交通条件。'],['保存出发时需要的信息','将真实票据、地址、办理入口和待确认问题放在一起。']];return {node:{id:gid,parent,trip:nodes[target].trip,title,kind:'guide',start:null,end:null,note:'',description:'围绕「'+nodes[target].title+'」整理的准备草案，具体要求待按实际情况核实。',steps:steps.map(([title,detail])=>({title,detail,done:false}))}};}
function send(raw){const text=raw.trim();if(!text)return;const c=conversation();c.draft='';el('ih-ai-input').value='';c.messages.push({role:'user',text});c.proposal=null;const scope=subtree(currentId);let target=currentId;const aliases=[['佛罗伦萨','florence'],['罗马','rome'],['乌菲齐','uffizi'],['博物馆','uffizi'],['自驾','drive'],['购物半日','shopping']];const namesScope=name=>['','把','给','为','在','补全','细化','调整','修改','将'].some(prefix=>text.startsWith(prefix+name));const named=scope.filter(n=>namesScope(n.title)).sort((a,b)=>b.title.length-a.title.length)[0];if(named)target=named.id;else for(const [alias,id] of aliases)if(namesScope(alias)&&scope.some(n=>n.id===id)){target=id;break;}const n=nodes[target];const p={target,baseRevision:revision,title:'建议这样调整',diffs:[],ops:[],request:text};const addDiff=(title,before,after)=>p.diffs.push({title,before,after});
 const dateMatch=text.match(/(?:(\d{4})[-年])?(\d{1,2})[-月](\d{1,2})(?:日|号)?/);
 if(/取消|删除|移除|不要/.test(text)){c.messages.push({role:'assistant',text:'这版还不能准确处理删除或否定条件。请直接描述希望保留的安排，或用“改名为…”、“增加…”提出一项修改。'});renderChat();return;}
 if((dateMatch&&/改|移|调整|推迟|提前|安排在/.test(text))||/推迟[一1]天|提前[一1]天/.test(text)){
  const date=dateMatch?(dateMatch[1]||(n.start||nodes.italy.start).slice(0,4))+'-'+dateMatch[2].padStart(2,'0')+'-'+dateMatch[3].padStart(2,'0'):n.start?shift(n.start,/提前/.test(text)?-1:1):null;
  if(!date||!validDate(date)){c.messages.push({role:'assistant',text:'这个日期还不能确定，请写成“改到 2026-10-04”这样的完整日期。'});renderChat();return;}
  p.title='平移这一部分的日期';p.ops=changesForShift(target,date);const affected=subtree(target).filter(x=>x.start);for(const x of affected.slice(0,5)){const delta=dayDiff(date,n.start);addDiff(x.title,dates(x),dates({...x,start:shift(x.start,delta),end:shift(x.end,delta)}));}if(!affected.length)addDiff(n.title,'日期待定',pretty(date,true));p.warning='共有 '+Math.max(affected.length,1)+' 项日期随之更新。预订与实际票据需要另行核对。';
 }else if(/改名|重命名/.test(text)){const title=text.split(/改名为|重命名为|改名成/)[1]?.trim();if(!title){c.messages.push({role:'assistant',text:'请用“改名为……”写出新的计划名称。'});renderChat();return;}p.ops.push({type:'set',id:target,field:'title',value:title.slice(0,100)});addDiff('计划名称',n.title,title.slice(0,100));
 }else if(/准备|购票|入场|租车|过关|海关|材料|办理/.test(text)){
  const topic=/海关|过关|入境/.test(text)?'border':/租车|取车|还车/.test(text)?'rental':/门票|购票|入场/.test(text)||ancestors(target).some(x=>x.id==='uffizi')?'museum':'general';
  if(n.kind==='guide'){const additions=[{title:'核对适用日期与个人条件',detail:'补充实际日期、人员和已有办理结果，再查证适用要求。',done:false},{title:'保存官方办理入口与材料清单',detail:'将后续核实到的官方说明、材料和截止时间附在这里。',done:false}].filter(s=>!n.steps.some(x=>x.title===s.title));if(!additions.length){c.messages.push({role:'assistant',text:'这些准备步骤已经在清单里。可以继续告诉我希望补充的具体问题。'});renderChat();return;}p.ops.push({type:'set',id:target,field:'steps',value:[...clone(n.steps),...additions]});addDiff('补充现有准备',n.steps.length+' 项',n.steps.length+additions.length+' 项：增加适用条件、材料与办理入口');}
  else{const title=topic==='museum'?'美术馆购票与入场准备':topic==='border'?'入境与海关准备':topic==='rental'?'租车与取还车准备':n.title+' · 出发前准备';const guide=makeGuide(target,title,topic);if(guide.existing){c.messages.push({role:'assistant',text:'「'+guide.existing.title+'」已与这部分关联。打开“准备”可以查看；进入这份准备后，我可以继续补充步骤。'});renderChat();return;}p.ops.push({type:'add',node:guide.node},{type:'relation',from:target,to:guide.node.id});p.title='增加一份关联准备';guide.node.steps.forEach(s=>addDiff(s.title,'',s.detail));p.warning='准备保存在同一趟旅行中，相关计划共用进度。内容待官方信息核实。';}
 }else if(/轻松|慢一点|慢慢|宽松|少走|休息/.test(text)&&!/增加|添加|加入/.test(text)){
  const description='以轻松的节奏探索，减少连续安排，保留休息和自由停留的时间。';p.ops.push({type:'set',id:target,field:'description',value:description},{type:'set',id:target,field:'pace',value:'relaxed'});addDiff(n.title,n.description,description);const flexible=subtree(target).filter(x=>x.kind==='activity'&&x.id!==target).at(-1);if(flexible){p.ops.push({type:'set',id:flexible.id,field:'optional',value:true});addDiff(flexible.title,flexible.optional?'可选安排':'原计划中的安排','保持可选，根据当天体力决定');}p.warning='只更新这部分的节奏和可选性，已有日期保持不变。';
 }else if(/补全|细化/.test(text)){
  const titles=['出发与交通衔接','围绕兴趣的重点体验','休息与自由探索'];const detail=['根据出发地和已有安排，补全到达方式与衔接时间。','先选择感兴趣的主题，再核实具体场所与预约条件。','预留一段自主安排的时间，途中可以继续调整。'];titles.forEach((title,i)=>{if(children(target).some(x=>x.title===title))return;const child={id:id(),parent:target,trip:n.trip,title,kind:'activity',start:n.start,end:n.start,note:'',description:detail[i],inherited:true,optional:i===2,slot:['出发前后','主要时段','自由安排'][i]};p.ops.push({type:'add',node:child});addDiff(title,'',detail[i]);});p.title='先补全三个可继续细化的安排';p.warning='使用当前范围的开始日期作为暂定日期，具体时间与地点尚待确认。';
 }else if(/增加|添加|加入|咖啡|购物|午餐/.test(text)){
  let title=text.replace(/^.*?(?:增加|添加|加入)(?:一段|一个|一项|一次)?/,'').trim();if(title===text&&/咖啡/.test(text))title='咖啡与休息';title=title.slice(0,80);if(children(target).some(x=>x.title===title)){c.messages.push({role:'assistant',text:'这里已经有同名安排，可以先进入它继续细化。'});renderChat();return;}const child={id:id(),parent:target,trip:n.trip,title,kind:'activity',start:n.start,end:n.start,note:'',description:'根据你的想法新增：'+text+'。地点和具体时间等待进一步选择。',inherited:true,optional:true,slot:/下午/.test(text)?'下午':'时间待定'};p.ops.push({type:'add',node:child});p.title='把这个想法加入当前计划';addDiff(title,'',pretty(n.start)+' · 可选安排 · 地点待补充');
 }else{
  p.title='先把这项需求记在计划里';p.ops.push({type:'set',id:target,field:'note',value:[n.note,text].filter(Boolean).join('\n')});addDiff('想法与备注',n.note||'暂无备注',text);p.warning='这版暂时无法完整理解并自动安排这项需求。采用后只会保存原文，便于后续细化。';
 }
 if(!p.ops.length){c.messages.push({role:'assistant',text:'这些安排已经存在，当前没有需要重复添加的内容。'});renderChat();return;}c.proposal=p;c.messages.push({role:'assistant',target:n.title,text:p.title==='先把这项需求记在计划里'?'这项需求需要进一步理解，可以先保存为当前计划的备注。':'我整理了一份修改预览。你可以采用，也可以继续告诉我哪里需要调整。'});renderChat();
}
function applyProposal(){const c=conversation(),p=c.proposal;if(!p||p.baseRevision!==revision){notice('建议已过期，请重新描述需求。');return;}checkpoint();for(const op of p.ops){if(op.type==='set')nodes[op.id][op.field]=clone(op.value);else if(op.type==='add')nodes[op.node.id]=clone(op.node);else if(op.type==='relation')relations.push({from:op.from,to:op.to});}expanded.add(p.target);c.messages.push({role:'assistant',target:nodes[p.target].title,text:'已采用这次修改。目录、日期和准备视图已同步，可以用页面顶部的“撤销”恢复。'});c.proposal=null;render();notice('已更新「'+nodes[p.target].title+'」。');}
// Mock maps show relationships only. Coordinates are normalized layout positions, not geography.
function mapPoints(n){const local=ancestors(n.id).some(x=>x.id==='florence');let points=subtree(n.id).filter(x=>x.location&&x.kind!=='place');if(!local)points=subtree(n.id).filter(x=>x.kind==='place'&&x.location);if(!points.length){const parent=ancestors(n.id).reverse().find(x=>x.location);if(parent)points=[parent];}return {local,points};}
function renderMap(n){const svg=el('ih-map');if(!globalThis.d3||!globalThis.TRAVEL_MAP_MOCK){el('ih-map-summary').textContent='示意地图资源未能加载，请检查 assets 文件。';return;}const {local,points}=mapPoints(n),data=globalThis.TRAVEL_MAP_MOCK[local?'florence':'italy'];const w=svg.getBoundingClientRect().width||540,h=420;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.replaceChildren();mapSvg=d3.select(svg);const g=mapSvg.append('g');const xy=p=>[p[0]*w,p[1]*h];const line=d3.line().x(p=>xy(p)[0]).y(p=>xy(p)[1]).curve(d3.curveBasis);
 g.selectAll('.mock-block').data(data.blocks).join('rect').attr('class','mock-block').attr('x',d=>d[0]*w).attr('y',d=>d[1]*h).attr('width',d=>d[2]*w).attr('height',d=>d[3]*h).attr('rx',6).attr('fill','var(--map-block)');
 g.selectAll('.mock-park').data(data.parks).join('ellipse').attr('class','mock-park').attr('cx',d=>d[0]*w).attr('cy',d=>d[1]*h).attr('rx',d=>d[2]*w).attr('ry',d=>d[3]*h).attr('fill','var(--map-park)');
 g.selectAll('.map-road').data(data.roads).join('path').attr('class','map-road major').attr('d',line).attr('stroke-width',8);
 if(data.river)g.append('path').attr('class','map-water').attr('d',line(data.river)).style('stroke-width',28);
 if(!local)g.append('path').attr('d',line([[.61,.73],[.63,.58],[.40,.46],[.37,.31]])).attr('fill','none').attr('stroke','var(--green)').attr('stroke-width',2).attr('stroke-dasharray','5 7').attr('opacity',.6);
 const labels=g.selectAll('.map-city').data(data.labels).join('text').attr('class','map-city').attr('x',d=>d.at[0]*w).attr('y',d=>d.at[1]*h).attr('text-anchor','middle').text(d=>d.name);
 const marks=g.selectAll('.map-point-group').data(points).join('g').attr('class','map-point-group').attr('transform',n=>'translate('+xy(n.location).join(',')+')');marks.append('circle').attr('class','map-point').attr('r',10).on('click',(event,p)=>{event.stopPropagation();selectMap(p.id);});marks.append('text').attr('class','map-poi-label').attr('x',14).attr('y',4).text(p=>p.locationLabel||p.title);
 mapZoom=d3.zoom().extent([[0,0],[w,h]]).scaleExtent([1,6]).on('zoom',event=>{g.attr('transform',event.transform);marks.select('circle').attr('r',10/event.transform.k).attr('stroke-width',3/event.transform.k);marks.select('text').style('font-size',12/event.transform.k+'px').attr('x',14/event.transform.k);labels.style('font-size',12/event.transform.k+'px');});mapSvg.call(mapZoom).on('dblclick.zoom',null);el('ih-map-caption').textContent=local?'佛罗伦萨 · 城市示意':'意大利 · 旅行示意';el('ih-map-summary').textContent=points.length+' 个示例地点 · 可拖动、缩放';const list=el('ih-map-items');list.replaceChildren();points.forEach((p,i)=>{const b=button('',()=>selectMap(p.id),'map-item');b.dataset.mapNode=p.id;b.setAttribute('aria-pressed',String(mapSelection===p.id));const body=create('span','map-item-text');body.append(create('span','',p.locationLabel||p.title),create('span','small',dates(p)));b.append(create('span','map-index',String(i+1)),body,create('span','row-arrow','›'));list.append(b);});const unknown=subtree(n.id).filter(x=>!x.location&&!planChildren(x.id).length&&!['guide','collection'].includes(x.kind));el('ih-map-missing').textContent=unknown.length?unknown.length+' 个安排还没有示例地点，可先在计划中继续细化。':'示例位置用于体验地图与计划联动，不代表真实坐标或路线。';el('ih-map-detail').hidden=true;if(!points.length)list.append(create('p','map-empty','这部分尚无示例地点，暂时显示旅行示意。'));if(mapSelection&&points.some(x=>x.id===mapSelection))selectMap(mapSelection);}
function selectMap(id){mapSelection=id;const n=nodes[id],area=el('ih-map-detail');area.replaceChildren();area.hidden=false;area.append(create('strong','',n.title),button('打开这部分计划 →',()=>go(id),'subtle-button'));root.querySelectorAll('[data-map-node]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mapNode===id)));}
// Direct manipulation and the AI preview both modify the same record table.
el('ih-add').addEventListener('click',openAdd);el('ih-inline-add').addEventListener('click',openAdd);el('ih-move').addEventListener('click',openMove);root.querySelectorAll('[data-close-form]').forEach(b=>b.addEventListener('click',closeForms));
el('ih-dates').addEventListener('click',()=>{closeForms();const n=nodes[currentId];el('ih-date-form').hidden=false;el('ih-start').value=n.start||'';el('ih-end').value=n.end||'';});
el('ih-date-form').addEventListener('submit',event=>{event.preventDefault();const start=el('ih-start').value,end=el('ih-end').value,n=nodes[currentId];if(!validDate(start)||!validDate(end)||end<start||dayDiff(end,start)>366){notice('请输入有效的起止日期，结束日期不得早于开始日期，范围最多一年。');return;}const ops=changesForShift(currentId,start);checkpoint();ops.forEach(op=>nodes[op.id][op.field]=op.value);n.end=end;n.inherited=false;closeForms();render();notice('日期已更新，子计划随之平移。');});
el('ih-add-form').addEventListener('submit',event=>{event.preventDefault();const title=el('ih-add-title').value.trim();if(!title)return;const parent=nodes[currentId],newId=id();checkpoint();nodes[newId]={id:newId,parent:parent.id,trip:parent.trip,title:title.slice(0,100),kind:'plan',start:parent.start,end:parent.end,note:'',description:'一个新想法，等待一起细化。',inherited:true};expanded.add(parent.id);closeForms();render();notice('已加入「'+parent.title+'」。');});
el('ih-move-form').addEventListener('submit',event=>{event.preventDefault();const target=el('ih-parent-select').value,n=nodes[currentId];if(!nodes[target]||subtree(n.id).some(x=>x.id===target)||target===n.parent)return;checkpoint();n.parent=target;subtree(n.id).forEach(x=>x.trip=nodes[target].trip);ancestors(n.id).forEach(x=>expanded.add(x.id));closeForms();render();notice('归属已更新，内容和日期保留。');});
el('ih-notes-form').addEventListener('submit',event=>{event.preventDefault();checkpoint();nodes[currentId].note=el('ih-notes').value.trim();render();notice('已保存当前计划的备注。');});
for(const v of ['plan','date','map','prep'])el('ih-'+v+'-view').addEventListener('click',()=>setMode(v));el('ih-related-open').addEventListener('click',()=>setMode('prep'));
el('ih-undo').addEventListener('click',()=>{if(!history.length)return;const s=history.pop();nodes=s.nodes;relations=s.relations;currentId=s.currentId;mode=s.mode;revision++;closeForms();render();notice('已撤销上一次修改。');});
el('ih-ai-input').addEventListener('input',()=>conversation().draft=el('ih-ai-input').value);el('ih-ai-form').addEventListener('submit',event=>{event.preventDefault();send(el('ih-ai-input').value);});el('ih-ai-input').addEventListener('keydown',event=>{if(event.key==='Enter'&&(event.metaKey||event.ctrlKey)){event.preventDefault();send(el('ih-ai-input').value);}});el('ih-ai-open').addEventListener('click',()=>openAI());el('ih-ai-prep').addEventListener('click',()=>openAI('增加这部分的出发前准备'));el('ih-refine').addEventListener('click',()=>openAI('补全这部分的具体安排'));
el('ih-zoom-in').addEventListener('click',()=>mapSvg&&mapZoom&&mapSvg.call(mapZoom.scaleBy,1.5));el('ih-zoom-out').addEventListener('click',()=>mapSvg&&mapZoom&&mapSvg.call(mapZoom.scaleBy,1/1.5));el('ih-map-fit').addEventListener('click',()=>mapSvg&&mapZoom&&mapSvg.call(mapZoom.transform,d3.zoomIdentity));
if(globalThis.matchMedia?.('(max-width:600px)').matches)el('ih-directory').open=false;
if(globalThis.ResizeObserver){let previous=0;new ResizeObserver(entries=>{const w=entries[0].contentRect.width;if(w!==previous){previous=w;if(mode==='map')renderMap(nodes[currentId]);}}).observe(el('ih-map'));}
render();
})();
