import React, { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowLeft, ChevronRight, ChevronLeft, Menu, Sparkles, MoreHorizontal, Plus, X, MapPin, ExternalLink, Expand, Check, RotateCcw, BookOpen, Footprints, PanelLeftClose } from 'lucide-react';
import { MapView } from './map';
import { articles, gallery, initialStops, places, planNames, scopeTitle, scopePath, notesForScope, type Scope, type Stop, type Tab } from './data';

type Route = { scope:Scope; tab:Tab; article?:string; poi?:string };
const defaultRoute:Route = {scope:'day',tab:'plan'};
const tripRoute:Route = {scope:'trip',tab:'plan'};
function parseRoute():Route {
  const q=new URLSearchParams(location.hash.slice(1));
  return {scope:['trip','day','walk',...places.map(p=>p.id)].includes(q.get('scope')||'')?q.get('scope') as Scope:'day',tab:['plan','content','map'].includes(q.get('tab')||'')?q.get('tab') as Tab:'plan',article:articles.some(a=>a.id===q.get('article'))?q.get('article')!:undefined,poi:places.some(p=>p.id===q.get('poi'))?q.get('poi')!:undefined};
}
function routeKey(r:Route){return new URLSearchParams(Object.entries(r).filter(([,v])=>v!==undefined)).toString();}
function Modal({title,onClose,children,className=''}:{title:string;onClose:()=>void;children:React.ReactNode;className?:string}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const d=ref.current!,opener=document.activeElement as HTMLElement|null;d.showModal();return()=>{d.close();requestAnimationFrame(()=>{if(opener?.isConnected&&!document.querySelector('dialog[open]'))opener.focus({preventScroll:true});});};},[]);
  return <dialog ref={ref} className={`dialog ${className}`} aria-label={title} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="dialog-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="关闭"><X size={20}/></button></div>{children}</dialog>;
}

export function App(){
  const [route,setRoute]=useState<Route>(parseRoute);
  const [stops,setStops]=useState<Stop[]>(()=>initialStops.map(s=>({...s})));
  const [checks,setChecks]=useState([false,false,false]);
  const [sidebar,setSidebar]=useState(false),[navCollapsed,setNavCollapsed]=useState(false);
  const [modal,setModal]=useState<'about'|'ai'|'add'|'edit'|null>(null);
  const [lightbox,setLightbox]=useState<number|null>(null),[pending,setPending]=useState<string|null>(null);
  const [toast,setToast]=useState(''),[undoStops,setUndoStops]=useState<Stop[]|null>(null);
  const [draft,setDraft]=useState(''),[aiReply,setAiReply]=useState(false),[editSummary,setEditSummary]=useState('');
  const [showMore,setShowMore]=useState(false),[mobilePreview,setMobilePreview]=useState(()=>new URLSearchParams(location.search).get('phone')==='1');
  const scrolls=useRef<Record<string,number>>({});
  const returnStack=useRef<{route:Route;button:HTMLElement|null}[]>([]);
  const routeRef=useRef(route);routeRef.current=route;
  const navigate=(next:Route,remember=true)=>{
    scrolls.current[routeKey(route)]=window.scrollY;
    const q=routeKey(next);history.pushState({},'',`#${q}`);setRoute(next);setSidebar(false);setShowMore(false);
    if(!remember)scrolls.current[q]=0;
  };
  useEffect(()=>{history.scrollRestoration='manual';const pop=()=>{scrolls.current[routeKey(routeRef.current)]=window.scrollY;setRoute(parseRoute());setSidebar(false);};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);
  useLayoutEffect(()=>{window.scrollTo({top:scrolls.current[routeKey(route)]||0,behavior:'instant'});},[route]);
  useEffect(()=>{if(!toast)return;const id=window.setTimeout(()=>setToast(''),4500);return()=>clearTimeout(id);},[toast]);
  const trip=route.scope==='trip', root=route.scope==='day', walk=route.scope==='walk', currentStop=stops.find(s=>s.id===route.scope), currentPlace=places.find(p=>p.id===route.scope);
  const title=scopeTitle(route.scope,stops);
  const path=scopePath(route.scope),parent=path.at(-2);
  const article=articles.find(a=>a.id===route.article);
  const visibleArticles=notesForScope(route.scope,stops);
  const articleIsRecommendation=!!article&&!visibleArticles.some(a=>a.id===article.id);
  const openArticle=(id:string)=>{returnStack.current.push({route,button:document.activeElement as HTMLElement});navigate({...route,tab:'content',article:id});};
  const closeArticle=()=>{const previous=returnStack.current.pop();navigate(previous?.route||{...route,tab:'content',article:undefined});requestAnimationFrame(()=>{if(previous?.button?.isConnected)previous.button.focus({preventScroll:true});});};
  const mapArticle=()=>{if(article)navigate({...route,tab:'map',article:undefined,poi:article.place==='day'?undefined:article.place});};
  const selected=places.find(p=>p.id===pending),added=stops.some(s=>!initialStops.some(i=>i.id===s.id));
  const saveAdd=()=>{if(!selected)return;if(stops.some(s=>s.id===selected.id)){setPending(null);return;}setUndoStops(stops.map(s=>({...s})));const next=[...stops];next.splice(1,0,{id:selected.id,time:'时间待定',title:selected.name,summary:'新增停留 · 可继续调整时间'});setStops(next);setPending(null);setToast('已加入安排');};
  const undo=()=>{if(!undoStops)return;setStops(undoStops);setUndoStops(null);setToast('已撤销，恢复原安排');};
  const reset=()=>{setStops(initialStops.map(s=>({...s})));setChecks([false,false,false]);setUndoStops(null);setPending(null);setModal(null);returnStack.current=[];navigate(defaultRoute,false);setToast('已重置样例');};
  const prior=returnStack.current.at(-1)?.route;

  return <div className={`app ${navCollapsed?'nav-collapsed':''} ${mobilePreview?'preview-phone':''}`}>
    {sidebar&&<button className="sidebar-scrim" aria-label="关闭目录" onClick={()=>setSidebar(false)}/>}
    <aside className={`sidebar ${sidebar?'open':''}`} aria-label="旅行目录">
      <a className="brand" href="#scope=trip&tab=plan" onClick={e=>{e.preventDefault();navigate(tripRoute);}}><span><ArrowUpRight size={22}/></span>行间</a>
      <div className="nav-section">我的旅行</div><button className={`trip-name ${trip?'active':''}`} aria-current={trip?'page':undefined} onClick={()=>navigate(tripRoute)}>{planNames.trip}</button>
      <button className={`nav-day ${root?'active':''}`} aria-current={root?'page':undefined} onClick={()=>navigate({...route,scope:'day',article:undefined,poi:undefined})}>{planNames.day}</button>
      <nav className="nav-children" aria-label="子计划"><button className={`nav-walk ${walk?'active':''}`} aria-current={walk?'page':undefined} onClick={()=>navigate({scope:'walk',tab:route.tab},false)}>{planNames.walk}</button><div className="nav-stops">{stops.map(s=><button key={s.id} className={route.scope===s.id?'active':''} aria-current={route.scope===s.id?'page':undefined} onClick={()=>navigate({scope:s.id,tab:'plan'},false)}>{scopeTitle(s.id,stops)}</button>)}</div></nav>
      <div className="sidebar-bottom"><button className="prototype-label" onClick={()=>setModal('about')}>交互稿 · 示例行程<ChevronRight size={13}/></button><button className="collapse-nav" aria-label="收起目录" onClick={()=>setNavCollapsed(true)}><PanelLeftClose size={17}/></button></div>
    </aside>
    <main>
      <header>
        <nav className="breadcrumbs" aria-label="计划路径"><button className="menu-toggle icon-button" aria-label="打开旅行目录" onClick={()=>{setSidebar(true);setNavCollapsed(false);}}><Menu size={19}/></button><div className="breadcrumb-trail">{path.map((scope,i)=><React.Fragment key={scope}>{i>0&&<ChevronRight size={14}/>} {i===path.length-1?<span aria-current="page">{scopeTitle(scope,stops)}</span>:<button onClick={()=>navigate({scope,tab:route.tab})}>{scopeTitle(scope,stops)}</button>}</React.Fragment>)}</div>{parent?<button className="breadcrumb-parent" aria-label={`返回${scopeTitle(parent,stops)}`} onClick={()=>navigate({scope:parent,tab:route.tab})}><ArrowLeft size={15}/>{scopeTitle(parent,stops)}</button>:<span className="breadcrumb-parent">{planNames.trip}</span>}</nav>
        <div className="header-actions"><button className="button ai-entry" aria-label="问问 AI" onClick={()=>{setModal('ai');setAiReply(false);}}><Sparkles size={16}/><span>问问 AI</span></button><button className="icon-button more-trigger" aria-label="更多操作" aria-expanded={showMore} onClick={()=>setShowMore(!showMore)}><MoreHorizontal size={20}/></button>{showMore&&<div className="more-menu"><button onClick={()=>{setModal('about');setShowMore(false);}}>本轮验收说明</button><button onClick={()=>{setMobilePreview(!mobilePreview);setShowMore(false);}}>{mobilePreview?'恢复桌面宽度':'预览手机宽度'}</button><button onClick={reset}>重置样例</button></div>}</div>
      </header>
      <div className="page-title"><p>{trip?'旅行总览 · 日期未定':root?'日期未定':walk?'上午散步 · 日期未定':`${currentStop?.time||'附近推荐'} · 佛罗伦萨`}</p><h1>{title}</h1></div>
      <nav className="tabs" aria-label="查看方式">{([['plan','计划'],['content','笔记'],['map','地图']] as [Tab,string][]).map(([value,label])=><button key={value} aria-current={route.tab===value?'page':undefined} className={route.tab===value?'active':''} onClick={()=>{returnStack.current=[];navigate({...route,tab:value,article:undefined});}}>{label}</button>)}</nav>

      {route.tab==='plan'&&<section className="view plan-view" aria-label="计划">
        {trip?<><div className="section-heading"><h2>旅行安排</h2><span>1 个目的地</span></div><ol className="plan-list"><li className="plan-row"><time>第一天</time><span className="step-number">1</span><button className="plan-title" onClick={()=>navigate(defaultRoute,false)}><h3>{planNames.day}</h3><p>1 项活动 · {planNames.walk}</p></button><button className="icon-button" aria-label={`打开${planNames.day}`} onClick={()=>navigate(defaultRoute,false)}><ChevronRight size={18}/></button></li></ol></>:root?<><div className="section-heading"><h2>当天安排</h2><span>1 项活动</span></div><ol className="plan-list"><li className="plan-row"><time>10:00</time><span className="step-number">1</span><button className="plan-title" onClick={()=>navigate({scope:'walk',tab:'plan'},false)}><h3>{planNames.walk}</h3><p>老桥、旧城街巷与圣十字广场 · {stops.length} 个子安排</p></button><button className="icon-button" aria-label={`打开${planNames.walk}`} onClick={()=>navigate({scope:'walk',tab:'plan'},false)}><ChevronRight size={18}/></button></li></ol></>:walk?<><button className="back-link" onClick={()=>navigate({scope:'day',tab:'plan'})}><ArrowLeft size={16}/>返回当天安排</button><div className="section-heading"><h2>散步安排</h2><button className="text-button" onClick={()=>setModal('add')}><Plus size={16}/>添加安排</button></div><ol className="plan-list">{stops.map((p,i)=><li className="plan-row" key={p.id}><time>{p.time}</time><span className="step-number">{i+1}</span><button className="plan-title" onClick={()=>navigate({scope:p.id,tab:'plan'},false)}><h3>{p.title}</h3><p>{p.summary}</p></button><button className="icon-button" aria-label={`打开${p.title}`} onClick={()=>navigate({scope:p.id,tab:'plan'},false)}><ChevronRight size={18}/></button></li>)}</ol><div className="plan-bottom"><span>{stops.length} 项安排 · 停留时间可调整</span>{undoStops&&<button className="text-button" onClick={undo}><RotateCcw size={15}/>撤销修改</button>}</div></>:<><button className="back-link" onClick={()=>navigate({scope:'walk',tab:'plan'})}><ArrowLeft size={16}/>返回散步安排</button><div className="leaf-details"><h2>{currentPlace?.name}</h2><p>{currentStop?.summary||currentPlace?.description}</p><div className="leaf-links"><button className="button" onClick={()=>openArticle(currentPlace?.article||'walk')}><BookOpen size={17}/>查看相关笔记</button><button className="button" onClick={()=>navigate({...route,tab:'map',poi:route.scope})}><MapPin size={17}/>在地图查看</button>{currentStop&&<button className="text-button" onClick={()=>{setEditSummary(currentStop.summary);setModal('edit');}}>编辑安排</button>}</div></div></>}
      </section>}

      {route.tab==='content'&&<section className="view content-view" aria-label="笔记">{article?<article className="reader"><div className="reader-nav"><button className="back-link" onClick={closeArticle}><ArrowLeft size={16}/>{prior?.tab==='map'?'返回地图':prior?.article?'返回上篇':prior?.tab==='plan'?'返回安排':'返回笔记'}</button><button className="text-button" onClick={mapArticle}><MapPin size={16}/>在地图查看</button></div><p className="note-origin">{articleIsRecommendation?`附近推荐 · ${places.find(p=>p.id===article.place)?.name||'相关地点'}`:`关联计划 · ${scopeTitle(article.plans[0],stops)}`}</p><p className="article-category">{article.category}</p><h2>{article.title}</h2><p className="article-lead">{article.summary}</p>
          {article.id==='uffizi'?<><p>这段散步里，可以先给乌菲齐的建筑留一点注意力。如果想进入展厅，把它单独安排成一段参观时间，会更从容。</p><figure><button className="article-image" onClick={()=>setLightbox(0)} aria-label="放大乌菲齐建筑图片"><img src={gallery[0].src} alt={gallery[0].alt}/><span><Expand size={16}/>查看大图</span></button><figcaption>乌菲齐建筑 · <a href={gallery[0].source} target="_blank" rel="noreferrer">乌菲齐官网</a></figcaption></figure><h3>从建筑开始</h3><p>先观察庭院两侧的立面、窗列和雕像。把经过这里和进入馆内参观分开考虑，就不用在散步途中赶着完成一整场参观。</p><h3>如果想多看一点绘画</h3><p>可以先浏览官方绘画专题，再选出你感兴趣的作品。图片和笔记放在一起，之后可以回到同一处继续读。</p><figure><button className="article-image" onClick={()=>setLightbox(1)} aria-label="放大绘画专题图片"><img src={gallery[1].src} alt={gallery[1].alt}/><span><Expand size={16}/>查看大图</span></button><figcaption>绘画专题配图 · <a href={gallery[1].source} target="_blank" rel="noreferrer">乌菲齐官网</a></figcaption></figure><button className="related-article" onClick={()=>openArticle('entry')}><div><span>相关指引</span><strong>预约与入馆</strong></div><ChevronRight size={19}/></button></>:
          article.id==='entry'?<><p>确定要进入馆内参观后，再补齐下面几项信息。先保留待办，不需要在起草行程时一次决定所有细节。</p><div className="checklist">{['确定参观日期','到官网核对开放与预约条件','把预约时间记入当天安排'].map((text,i)=><label key={text}><input type="checkbox" checked={checks[i]} onChange={e=>setChecks(checks.map((v,k)=>k===i?e.target.checked:v))}/><span>{text}</span></label>)}<p className="checklist-progress">我的进度 · {checks.filter(Boolean).length} / 3</p></div><p>实际开放时间、票种和入馆要求，以所选日期的官方信息为准。</p><a className="source-button" href="https://www.uffizi.it/en/the-uffizi" target="_blank" rel="noreferrer">打开乌菲齐官网<ExternalLink size={16}/></a></>:
          article.id==='pause'?<><p>先在上午留出一段休息时间，比提前排满每一站更灵活。可以从地图里的附近地点开始看看，再根据当天的营业情况选择。</p><h3>途中可以留意</h3><p>Alimentari Uffizi 是现有地图样本中的一处餐饮地点。可以先保存为备选，营业情况和菜单仍需核实。</p><button className="button" onClick={()=>navigate({...route,tab:'map',article:undefined,poi:'cafe'})}><MapPin size={17}/>查看附近位置</button></>:
          <><p>从老桥出发，穿过旧城街巷，到圣十字广场结束。先把三个片段串起来，再按自己的兴趣决定中间在哪里多停一会儿。</p><h3>1. 老桥与河景</h3><p>从桥和阿尔诺河开始。先看看两岸，让散步有一个从容的起点。</p><h3>2. 穿过旧城街巷</h3><p>沿已有步行路径进入 Borgo de’ Greci 一带。领主广场和乌菲齐可作为附近看点，是否停留可以另作选择。</p><h3>3. 圣十字广场</h3><p>到广场后保留自由时间。步行估计不包含拍照、休息或参观停留。</p><button className="source-button" onClick={()=>navigate({...route,tab:'map',article:undefined,poi:undefined})}><Footprints size={17}/>查看这段散步路线</button></>}
          <details className="source-details"><summary>来源与说明</summary><p>行程时间与推荐理由是本轮固定设计样例。路线及地点来自 2026-09-08 保存的 Geoapify / OpenStreetMap 数据；图片来自乌菲齐官网。不表示已核实当日开放或完成预订。</p><a href={article.id==='uffizi'||article.id==='entry'?'https://www.uffizi.it/en/the-uffizi':'https://www.openstreetmap.org/'} target="_blank" rel="noreferrer">查看资料来源<ExternalLink size={14}/></a></details>
        </article>:<><div className="section-heading"><h2>{trip?'旅行笔记':root?'这一天的笔记':walk?'散步笔记':'相关笔记'}</h2><span>{visibleArticles.length} 篇</span></div><div className="content-list">{visibleArticles.map(a=><button className={`content-item ${a.photo?'has-photo':''}`} onClick={()=>openArticle(a.id)} key={a.id}><div><span className="article-category">{a.category}</span><h3>{a.title}</h3><p>{a.summary}</p><span className="note-owner">{scopeTitle(a.plans[0],stops)}</span>{a.id==='entry'&&<span className="content-check-count">{checks.filter(Boolean).length}/3 项完成</span>}</div>{a.photo?<img src={a.photo} alt="乌菲齐建筑预览"/>:<ChevronRight size={20}/>}</button>)}</div>{visibleArticles.length===0&&<p className="empty-notes">暂无关联笔记</p>}{!trip&&!root&&<button className="back-link view-all" onClick={()=>navigate({scope:'day',tab:'content'})}>查看这一天的全部笔记<ChevronRight size={16}/></button>}</>}
      </section>}

      <div hidden={route.tab!=='map'}>{(trip||root)&&<div className="trip-map-context"><span>{planNames.walk}</span><button className="text-button" onClick={()=>navigate({scope:'walk',tab:'map'})}>查看散步地图<ChevronRight size={16}/></button></div>}<MapView active={route.tab==='map'} scope={route.scope} selectedId={route.poi} stops={stops} stale={added} onSelect={id=>navigate({...route,poi:id,article:undefined})} onRead={openArticle} onAdd={setPending} onOpenPlan={id=>navigate({scope:id as Scope,tab:'plan'})}/></div>
      <footer className="mobile-review"><button onClick={()=>setModal('about')}>交互稿 · 示例行程</button>{mobilePreview&&<button onClick={()=>setMobilePreview(false)}>退出手机预览</button>}</footer>
    </main>
    {lightbox!==null&&<Modal title={gallery[lightbox].caption} className="lightbox" onClose={()=>setLightbox(null)}><img src={gallery[lightbox].src} alt={gallery[lightbox].alt}/><div className="lightbox-foot"><button className="icon-button" aria-label="上一张图片" onClick={()=>setLightbox((lightbox+gallery.length-1)%gallery.length)}><ChevronLeft/></button><span>{lightbox+1} / {gallery.length}</span><a href={gallery[lightbox].source} target="_blank" rel="noreferrer">图片来源<ExternalLink size={14}/></a><button className="icon-button" aria-label="下一张图片" onClick={()=>setLightbox((lightbox+1)%gallery.length)}><ChevronRight/></button></div></Modal>}
    {pending&&selected&&<Modal title="加入安排" onClose={()=>setPending(null)}><div className="proposal"><p className="article-category">新增停留</p><h3>{selected.name}</h3><p>{selected.description}</p><div className="insert-preview"><span>{stops[0]?.title}</span><ChevronRight size={15}/><strong>{selected.name}</strong><ChevronRight size={15}/><span>旧城街巷</span></div><p className="subtle">加入“从老桥到圣十字”，时间待定。加入后需要更新步行路径；本交互稿不重新计算路线。</p></div><div className="dialog-actions"><button className="button" onClick={()=>setPending(null)}>取消</button><button className="button primary" onClick={saveAdd}>加入安排</button></div></Modal>}
    {modal==='about'&&<Modal title="本轮验收" onClose={()=>setModal(null)}><div className="review-guide"><p>先看安排，再读笔记，最后去地图看看它们如何连在一起。</p><ol><li>计划：从当天进入散步，再查看三个子安排，标题和层级是否清楚？</li><li>笔记：当前只展示关联笔记；乌菲齐介绍从地图的附近推荐进入。</li><li>地图：区分已安排地点和附近推荐，打开详情后返回。</li><li>加入一个推荐，再撤销，看看计划与地图是否一致。</li><li>切换手机宽度，检查阅读与操作是否顺手。</li></ol><p className="subtle">这是独立交互稿。修改只在当前页面有效，刷新重置；使用已保存的真实路线和图片，推荐为固定样例，AI 仅演示入口。</p><div className="button-row"><button className="button" onClick={()=>{setMobilePreview(!mobilePreview);setModal(null);}}>{mobilePreview?'恢复桌面宽度':'预览手机宽度'}</button><button className="button" onClick={reset}><RotateCcw size={15}/>重置样例</button></div></div></Modal>}
    {modal==='ai'&&<Modal title={`讨论：${title}`} className="ai-dialog" onClose={()=>setModal(null)}><p className="subtle">交互稿中的 AI 用于演示讨论入口，不发送模型请求。</p>{aiReply&&<div className="ai-answer"><h3>可以先保留这三个片段</h3><p>如果希望多看一些艺术内容，可以先读乌菲齐介绍，再决定是否把它加入上午安排。</p><button className="button" onClick={()=>{setModal(null);openArticle('uffizi');}}>阅读乌菲齐介绍<BookOpen size={16}/></button></div>}<label className="field">想怎么调整？<textarea rows={3} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="例如：想多看一点艺术，但不要太赶"/></label><div className="dialog-actions"><button className="button primary" onClick={()=>setAiReply(true)} disabled={!draft.trim()}>查看示例回应</button></div></Modal>}
    {modal==='add'&&<Modal title="添加安排" onClose={()=>setModal(null)}><p className="subtle">从这段散步附近的地点开始。</p><div className="add-choices">{places.filter(p=>!stops.some(s=>s.id===p.id)).map(p=><button key={p.id} onClick={()=>{setModal(null);setPending(p.id);}}><span><strong>{p.name}</strong><small>{p.kind}</small></span><Plus size={18}/></button>)}</div></Modal>}
    {modal==='edit'&&<Modal title="编辑安排" onClose={()=>setModal(null)}><label className="field">一句摘要<textarea rows={3} maxLength={160} value={editSummary} onChange={e=>setEditSummary(e.target.value)}/></label><div className="dialog-actions"><button className="button" onClick={()=>setModal(null)}>取消</button><button className="button primary" onClick={()=>{setUndoStops(stops.map(s=>({...s})));setStops(stops.map(s=>s.id===route.scope?{...s,summary:editSummary}:s));setModal(null);setToast('已更新摘要');}}>保存</button></div></Modal>}
    {toast&&<div className="toast" role="status"><Check size={17}/>{toast}{undoStops&&<button onClick={undo}>撤销</button>}</div>}
  </div>;
}
